language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

install:
  - npm -d install

script:
  - npm run cover

after_success:
  - ./node_modules/.bin/coveralls                 < coverage/lcov.info || true
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info || true
