language: node_js

node_js:
  - "5.6"
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"

install:
  - npm install

script:
  - npm run cover

after_success:
  - ./node_modules/.bin/coveralls                 < coverage/lcov.info || true
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info || true
